version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_doannganh2
    restart: always
    environment:
      POSTGRES_USER: duc
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: doannganh_db
    ports:
      - "5433:5432" # Sử dụng cổng 5433 để tránh xung đột
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: