spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/doannganh_prod}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
    
  jpa:
    hibernate:
      ddl-auto: validate  # Don't auto-create in production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  sql:
    init:
      mode: never  # Don't run data.sql in production

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# Fixed YAML logging structure
logging:
  level:
    com:
      doananganh:
        backend: INFO
    org:
      springframework:
        web: WARN
      hibernate: WARN

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized