spring:
  config:
    activate:
      on-profile: docker
      
  datasource:
    url: jdbc:postgresql://postgres:5432/doannganh_db
    username: postgres
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create-drop  # Let schema.sql handle structure
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

server:
  port: 8080

# Docker logging
logging:
  level:
    com:
      doananganh:
        backend: DEBUG
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG

# Health check endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always