# Main Spring Boot Configuration
spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never  # DISABLED - let JPA handle schema creation
      # schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql

server:
  port: 8081
  # servlet:
  #   context-path: /api  # DISABLED for easier testing

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    com:
      doananganh:
        backend: INFO

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/doannganh_db
    username: postgres
    password: password

logging:
  level:
    com:
      doananganh:
        backend: DEBUG

---
# Docker Profile  
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/doannganh_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop  # Let Hibernate create schema
    show-sql: true
  sql:
    init:
      mode: never  # Disable schema.sql execution