# Main Spring Boot Configuration - PostgreSQL Only
spring:
  application:
    name: task-management-backend
  
  profiles:
    active: postgresql  # Chỉ dùng PostgreSQL
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/doannganh_db
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  
  # Flyway Configuration for Database Migrations
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway handles schema, Hibernate validates only
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: never  # Let Flyway handle all schema creation

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    com:
      doananganh:
        backend: INFO

# JWT Configuration
jwt:
  secret: "mySecretKey123456789012345678901234567890"
  expiration: 86400000 # 24 hours in milliseconds

# Swagger/OpenAPI Configuration  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

---
# PostgreSQL Profile (Production-ready)
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/doannganh_db
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5 
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    
  jpa:
    hibernate:
      ddl-auto: validate  # Production mode - validate only
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    com:
      doananganh:
        backend: INFO
    org:
      flywaydb: INFO

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/doannganh_db
    username: postgres
    password: password

logging:
  level:
    com:
      doananganh:
        backend: DEBUG

# JWT Configuration
jwt:
  secret: "mySecretKey123456789012345678901234567890"
  expiration: 86400000 # 24 hours in milliseconds

# Swagger/OpenAPI Configuration  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

---
# Docker Profile  
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/doannganh_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop  # Let Hibernate create schema
    show-sql: true
  sql:
    init:
      mode: never  # Disable schema.sql execution